import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Product",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "Blog",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Connect",
    link: "contact",
  },
  {
    _id: 1005,
    title: "About ",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: bac3,
    productName: "Lenovo Laptop @80% OFF",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "Lenovo Yoga Book 9",
    price: "350.00",
    color: "Black",
    badge: true,
    brand: "Lenovo",
    des: "13th Gen Intel Evo Core i7 Dual 13.3 2.8K OLED Display(2x33.7cm) with Pen+Keyboard|16GB/1TB SSD/Win 11/Office 2021/5.0MP IR Camera/360° B&W Rotating Soundbar/Teal/1.34Kg,82YQ001DIN",
    cat: "Lenovo",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology", value: "13th Gen Intel" },
      { label: "speed ", value: "Fast processor" },

      { label: "Storage ", value: "16GB/1TB       " },
      { label: "Design", value: "Dual Screen | Touchscreen Anti-Fingerprint Glass | 1.59 cm Thin and 1.34 kg Light " },
      {
        label: "Display ",
        value: "Dual screen 2x13.3 2.8K (2880x1800) OLED Brightness: 400 nits ",
      },
      { label: "Battery ", value: "75Wh | 8 Hours | Rapid Charge Express " },
      { label: "Camera  ", value: "5.0MP Camera with E-Shutter for Privacy   " },
      { label: "Audio  ", value: " 4x 2W Stereo Speakers| 2Wx2 (   " },
    ],
  },
  {
    _id: "202",
    img: IMPRIMANTE_PANTUM_BM5100FDW,
    productName: "Dell [Smartchoice] ",
    price: "450",
    color: "Black",
    badge: true,
    brand: "Dell",
    des: "Thin & Light Laptop, 12th Gen Intel Core i3-1215U Processor/8GB/512GB SSD/Intel UHD Graphics/15.6 (39.62cm) FHD/Windows 11 + MSO'21/15 Month McAfee/Spill-Resistant KB/Grey/1.48kg",
    cat: "Dell",
    pdf: pdf1,
    ficheTech: [
      { label: "Processor", value: "Intel Core i3-1215U 12th Generation  " },
      { label: "RAM & Storage ", value: "8 GB, 1 x 8 GB, DDR4, 2666 MHz" },

      {
        label: "Software",
        value: "Pre-Loaded Windows 11 Home with Lifetime Validity | MS Office Home and Student 2021 with lifetime validity| McAfee Multi-Device Security 15-month subscription",
      },
      { label: "Graphics & Keyboard", value: "Integrated Onboard Graphics & Standard Keyboard " },
      {
        label: "Ports ",
        value: "2 USB 3.2 Gen 1 ports, 1 USB 2.0 port, 1 Headset jack, 1 HDMI 1.4 port, 1 SD 3.0 card slot, 1 Flip-Down RJ-45 port 10/100/1000 Mbps       ",
      },
      
    ],
  },

  {
    _id: "203",
    img: IMPRIMANTE_PANTUM_BP5100DN,
    productName: "Dell Inspiron 7430",
    price: "450",
    color: "Grey",
    badge: true,
    brand: "Dell",
    des: "2in1 Touch 13th Gen Laptop, Intel Core i3-1315U Processor, 8GB, 256Gb SSD, 14.0 (35.56cm) FHD+ Display, Win 11 + MSO'21, Backlit KB + FingerPrintReader, Silver,Thin & Light- 1.58kg",
    cat: "Dell",
    pdf: pdf1,
    ficheTech: [
      { label: "Processor ", value: "Intel Core i3-1315U (up to 4.50 GHz, 10MB Cache, 6 Cores) // RAM: 8GB 4800MHz LPDDR5 Memory Onboard" },
      { label: "Software", value: "Pre-Loaded Windows 11 Home with Lifetime Validity | MS Office Home and Student 2021 with lifetime validity| McAfee Multi Device Security 15-month subscription" },

      {
        label: "Display",
        value: "14.0 FHD+ WVA with ComfortView Support 250 nits Touch // Keyboard: Backlit Keyboard + Fingerprint Reader",
      },
      { label: "Port", value: " HDMI 1.4, (2) Intel Thunderbolt 4.0, (1) USB 3.2 Gen 1 Type-A, SD card reader, (1) Universal Audio Jack" },
    ],
  },
  {
    _id: "2005",
    img: IMPRIMANTE_PANTUM_M6609N,
    productName: "ASUS Vivobook 15 ",
    price: "330",
    color: "BLue",
    badge: true,
    brand: "Asus",
    des: "Thin and Light Laptop,Intel Core i5-12500H 12th Gen, 15.6 (39.62 cm) FHD, (16GB RAM/512GB/Win11/Office 2021/Blue/1.7 kg), X1502ZA-EJ541WS",
    cat: "Asus",
    pdf: pdf1,
    ficheTech: [
      { label: "Processor	", value: "Intel Core i5-12500H Processor 2.5 GHz (18M Cache, up to 4.5 GHz, 4P+8E cores) Strong Performance,Enhanced Gaming Experience.      " },
      { label: "Storage	", value: "512GB M.2 NVMe PCIe 3.0 SSD | Memory: 16GB (8GB DDR4 on board + 8GB SO-DIMM) DDR4   " },
      { label: "Display	", value: "1.99 ~ 1.99 cm | 1.70 kg | Thin and Light Laptop | 42WHrs, 3S1P, 3-cell Li-ion | Up to 6 hours battery life ;Note: Battery life depends on conditions of usage      " },
      { label: "Design", value: "15.6-inch (35.56cm), FHD (1920 x 1080) 16:9 aspect ratio, LED Backlit, 60Hz refresh rate, 220nits, 45% NTSC color gamut,      " },
    ],
  },

  {
    _id: "20005",
    img: IMPRIMANTE_PANTUM_P3300DN,
    productName: "ASUS TUF F15 Gaming Laptop",
    price: "250",
    color: "Black",
    badge: true,
    brand: "Asus",
    des: "Intel Core i5-11400H 11th Gen, 15.6-inch (39.62 cm) FHD 144Hz,(16GB RAM/512GB SSD/4GB NVIDIA GeForce RTX 2050/Windows 11/ RGB Backlit KB/Black/2.30 kg), FX506HF-HN025W",
    cat: "Asus",
    pdf: pdf1,
    ficheTech: [
      { label: "Processor	", value: "Intel Core i5-11400H Processor 2.7 GHz (12M Cache, up to 4.5 GHz, 6 Cores) efficient multitasking, Improved multimedia tasks etc.      " },
      { label: "Storage	", value: "512GB PCIe 3.0 NVMe M.2 SSD with additional 1x M.2 Slot for SSD Storage expansion |Memory: 16GB SO-DIMM DDR4 3200MHz Support Up to 32GB 2x SO-DIMM slots      " },
      { label: "Display	", value: "144Hz Refresh Rate, 15.6 inch (39.62 cms) FHD (1920 x 1080) 16:9 250nits,vIPS-level Anti-glare display, Contrast Ratio: 1000:1 with Adaptive-Sync;      " },
      { label: "Operating system		", value: "Windows 11 Homewith Lifetime Validity      " },
    ],
  },

  {
    _id: "206",
    img: IMPRIMANTE_PANTUM_P3300DW,
    productName: "HP Laptop 15s",
    price: "200",
    color: "Silver",
    badge: true,
    brand: "HP",
    des: "AMD Ryzen 3 5300U, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, AMD Radeon Graphics, Thin & Light, Dual Speakers (Win 11, MSO 2019, Silver, 1.69 kg), eq2143AU",
    cat: "HP",
    pdf: pdf1,
    ficheTech: [
      { label: "Processor	", value: "8 threads and 4MB L3 cache deliver powerful performance and swift responsiveness. The AMD Radeon graphics help you experience crisp visuals with vivid clarity.      " },
      { label: "Memory	", value: "GB DDR4 RAM integrates a higher-bandwidth memory for smooth functioning. The high-speed 512GB PCIe NVMe M.2 SSD      " },
      { label: "Display	", value: "The 15.6-inch, FHD, 250-nit, anti-glare, and micro-edge display is engineered for high-quality viewing with stunning clarity.      " },
      { label: "Connectivity		", value: "Wi-Fi 5 (1x1) and Bluetooth 4.2 ensure an uninterrupted and seamless experience. Enjoy effortless connectivity with 1 x USB Type-C, 2 x USB Type-A, and 1 x HDMI 1.4b ports.      " },
    ],
  },

  {
    _id: "207",
    img: IMPRIMANTE_PANTUM_P2509W,
    productName: "HP Victus Gaming Laptop",
    price: "300",
    color: "Blue",
    badge: true,
    brand: "HP",
    des: "AMD Ryzen 5 5600H, 4GB RTX 3050 GPU, 15.6-inch (39.6 cm), FHD, IPS, 144Hz, 16GB DDR4, 512GB SSD, Backlit KB, B&O, 9ms Response time, Dual Speakers (Blue, 2.37 kg), fb0106AX",
    cat: "HP",
    pdf: pdf1,
    ficheTech: [
      { label: "Processor		", value: "Experience the power of 12 threads and a 16MB L3 cache, designed for serious gaming and multitasking. Stay cool under pressure with the updated thermals      " },
      { label: "Graphic Card	", value: "Unlock an immersive gaming experience with graphics that deliver enhanced 3D rendering and hyper-efficient data processing      " },
      { label: "Memory	", value: "Upgrade your system with 512GB PCIe Gen4 NVMe TLC M.2 SSD and 16GB DDR4 RAM. Conquer opponents with improved responsiveness and ample storage for all your gaming needs.       " },
      { label: "Display		", value: "Enjoy the immersive 15.6” FHD display with a micro-edge bezel and anti-glare screen delivering high-quality visuals with a rapid 144Hz refresh rate and 9ms response time      " },
    ],
  },

  {
    _id: "208",
    img: IMPRIMANTE_PANTUM_P2509,
    productName: "HP OMEN Gaming Laptop",
    price: "450",
    color: "Red",
    badge: true,
    brand: "HP",
    des: "AMD Ryzen 7 7840HS, 8GB RTX 4060 GPU, 16.1 (40.9 cm), FHD, IPS, 165 Hz, 300 nits, 16GB DDR5, 1TB SSD, RGB KB, 7ms Response time (Win 11, Black, 2.32 kg), xd0020AX",
    cat: "HP",
    pdf: pdf1,
    ficheTech: [
      { label: "Processor	", value: "Elevate your gaming with 16 threads and 16MB L3 cache, as this processor offers efficient multitasking with updated thermals to maintain optimal performance.      " },
      { label: "Memory	", value: " 16GB DDR5 RAM and 1TB PCIe Gen4 NVMe M.2 SSD ensure smooth gameplay and deliver fast loading times for all your games and applications." },
      { label: "Display		", value: "Immerse yourself in the 16.1” FHD display with 7ms response time. The anti-glare screen enhances your viewing experience, making every game feel real and immersive.      " },
      { label: "Graphic Card", value: "Experience gaming with dedicated graphics that deliver enhanced 3D rendering and AI-accelerated performance for an immersive gaming experience.      " },
    ],
  },
  {
    _id: "233",
    img: bac3,
    productName: "ThinkBook 16 40.64cms - 13th Gen Intel i7",
    price: "250",
    color: "White",
    badge: true,
    brand: "Lenovo",
    des: "he Lenovo ThinkBook 16 Gen 6 laptop offers a state-of-the-art upgrade to your daily tasks. Featuring 13th Gen Intel® Core™ processors, with the availability of cutting-edge Intel® Evo™ or Intel vPro® Essentials platforms",
    cat: "Lenovo",
    pdf: pdf1,
    ficheTech: [],
  },
  {
    _id: "220",
    img: bac4,
    productName: "Dell XPS Laptops & 2-in-1 PCs",
    price: "225.00",
    color: "White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Dell",
  },
  {
    _id: "221",
    img: ruban3,
    productName: "Dell 15 Thin & Light Laptop",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Dell",
  },
  {
    _id: "215",
    img: ruban4,
    productName: "HP Chromebook x360",
    price: "125.00",
    color: "Red",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "HP",
  },
  {
    _id: "216",
    img: encre1,
    productName: "ASUS Vivobook Go 15 ",
    price: "320.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Asus",
  },
  {
    _id: "209",
    img: encre2,
    productName: "Lenovo Tab Plus ",
    price: "250.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Lenovo",
  },
];
